name = "MixedLRMoE"
uuid = "5cfe8048-c24a-4519-9529-e8ccde501b98"
authors = ["sparktseung <hi@sparktseung.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LRMoE = "b6847444-3cfa-4637-857f-9c8c615f8351"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
