name = "MixedLRMoE"
uuid = "5cfe8048-c24a-4519-9529-e8ccde501b98"
authors = ["sparktseung <hi@sparktseung.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LRMoE = "b6847444-3cfa-4637-857f-9c8c615f8351"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
